#Takes individual Recordings generated by piedPiperRecordingParser and creates graphed waveforms
#for visual analysis. Must be used after piedPiperRecordingParser is run

import matplotlib.pyplot as plt
import numpy as np
from numpy import genfromtxt
import os
import csv

basepath = 'D:\\Rec\\' #the path for where the recordings are stored

for file in os.listdir(basepath):	#iterate through all files in directory
	path = basepath+file	#add file name to basepath
	if os.path.splitext(path)[1] == '.txt':	#only operate on txt files
		data = genfromtxt(path,delimiter=',')	#import txt data into array
		plt.plot(data,label='Insect')	#create plot
		plt.xlabel('Time')
		plt.ylabel('Amplitude')
		plt.title(file)
		plt.legend()
		save_path = file	#sets the save path for saving plots
		save_path = os.path.splitext(save_path)[0]	#separate extension
		save_path = save_path+'.png'	#save as image file
		print(save_path)
		plt.savefig(os.path.join(basepath+'Plots',save_path))	#save the plot
		plt.close()
